/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anwser: typeof import('./src/components/anwser.vue')['default']
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    Person: typeof import('./src/components/Person.vue')['default']
    TagInput: typeof import('./src/components/TagInput.vue')['default']
  }
}
